apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
  compileSdkVersion 35

  namespace "com.abc.core.jsengine"
  ndkVersion "28.2.13676358"

  sourceSets {
    main.java.srcDirs += "../jsengine-java/src/main/java/"
    androidTest.java.srcDirs += "../jsengine-java/src/test/java/"
  }

  dependencies {
    testImplementation 'junit:junit:4.13.1'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
  }

  compileOptions {
    sourceCompatibility 1.8
    targetCompatibility 1.8
  }

  defaultConfig {
    minSdkVersion 21
    targetSdkVersion 35
    versionCode 1
    versionName "1.0"
    ndk {
      // abiFilters('arm64-v8a', 'x86_64')
    }
    externalNativeBuild {
      cmake {
        arguments '-DANDROID_TOOLCHAIN=clang', '-DANDROID_STL=c++_static'
        cFlags '-std=c99', '-fstrict-aliasing', '-DDUK_USE_DEBUGGER_SUPPORT', '-DDUK_USE_INTERRUPT_COUNTER', '-DDUK_USE_DEBUGGER_INSPECT', '-DDUK_USE_DEBUGGER_THROW_NOTIFY', '-DDUK_USE_DEBUGGER_PAUSE_UNCAUGHT', '-DDUK_USE_DEBUGGER_DUMPHEAP', '-Werror', '-Wno-implicit-function-declaration', '-Wno-implicit-float-conversion', '-Wno-pointer-to-int-cast'
        cppFlags '-std=c++11', '-fstrict-aliasing', '-fexceptions', '-Werror'
      }
    }

    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    // ProGuard rules for consumer apps
    consumerProguardFiles 'consumer-proguard-rules.pro'
  }
  packagingOptions {
    jniLibs {
      useLegacyPackaging = true
    }
  }
  buildTypes {
    release {
      minifyEnabled false
      // proguardFiles not needed - library is not minified, only consumer apps are
      externalNativeBuild {
        cmake {
          arguments '-DCMAKE_BUILD_TYPE=MinSizeRel'
          cFlags '-g0', '-Os', '-fomit-frame-pointer', '-DNDEBUG', '-fvisibility=hidden', '-Werror'
          cppFlags '-g0', '-Os', '-fomit-frame-pointer', '-DNDEBUG', '-fvisibility=hidden', '-Werror'
        }
      }
    }
    debug {
      externalNativeBuild {
        cmake {
          cFlags '-g', '-DDEBUG', '-Werror'
          cppFlags '-g', '-DDEBUG', '-Werror'
        }
      }
    }
  }
  externalNativeBuild {
    cmake {
      path "src/main/jni/CMakeLists.txt"
    }
  }
}

// Task to copy license files into AAR assets
task copyLicenseFiles(type: Copy) {
  from("${rootDir}/LICENSE") {
    rename { "LICENSE" }
  }
  from("${rootDir}/NOTICE") {
    rename { "NOTICE" }
  }
  from("${rootDir}/THIRD_PARTY_LICENSES") {
    rename { "THIRD_PARTY_LICENSES" }
  }
  into "${projectDir}/src/main/assets/licenses"
}

// Ensure license files are copied before building
preBuild.dependsOn copyLicenseFiles

// Task to generate sources JAR
task androidSourcesJar(type: Jar) {
  archiveClassifier.set('sources')
  from android.sourceSets.main.java.srcDirs
}

afterEvaluate {
  publishing {
    publications {
      release(MavenPublication) {
        groupId = 'com.abc.core'
        artifactId = 'jsengine'
        version = '1.0.4'
        artifact("$buildDir/outputs/aar/${project.name}-release.aar")
        artifact androidSourcesJar

        pom {
          name = 'JSEngine'
          description = 'Java and Android bindings for JavaScript engines (QuickJS/Duktape) with 16KB page size support'
          url = 'https://github.com/yourusername/jsengine'

          licenses {
            license {
              name = 'The Apache License, Version 2.0'
              url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
            }
          }

          developers {
            developer {
              id = 'abc'
              name = 'ABC'
              email = 'dev@abc.com'
            }
          }
        }
      }
    }

    repositories {
      mavenLocal()
      // maven { url = uri("...") } // For remote publishing
    }
  }
}
